on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

name: Behat Test 👨‍🔧

jobs:
  Behat-Test:
    runs-on: ubuntu-latest
    name: Behat Tests - PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    steps:
    - name: Check out source code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '${{ matrix.php }}'
        coverage: none
        tools: composer
        extensions: pcntl, curl, sqlite3, zip, dom, mbstring, json, xml

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-interaction

    - name: Test
      run: |
        sudo -E ./vendor/bin/behat