on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

name: Behat Test 👨‍🔧

jobs:
  Behat-Test:
    runs-on: ubuntu-latest
    name: Behat Tests - PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    steps:
    - name: Check out source code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '${{ matrix.php }}'
        coverage: none
        tools: composer
        extensions: pcntl, curl, sqlite3, zip, dom, mbstring, json, xml

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Set up Composer caching
      uses: actions/cache@v4
      env:
        cache-name: cache-composer-dependencies
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Update docker
      run: |
        sudo apt remove --purge nginx nginx-common docker docker-engine docker.io docker-ce containerd runc
        curl -fsSL https://get.docker.com/ | sudo bash
        sudo systemctl restart docker.service

    - name: Install docker-compose
      run: |
        rm -rf /usr/local/bin/docker-compose
        VERSION=$(curl --silent "https://api.github.com/repos/docker/compose/releases/latest" |
          grep '"tag_name":' |
          sed -E 's/.*"([^"]+)".*/\1/'
        )
        sudo curl -L "https://github.com/docker/compose/releases/download/$VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: Install dependencies
      run: |
        cd "$GITHUB_WORKSPACE/.."
        git clone https://github.com/EasyEngine/easyengine.git easyengine --depth=1
        cd easyengine
        rm -rf features
        cp -R $GITHUB_WORKSPACE/features .
        sed -i 's/\(easyengine\/.*\):\ \".*\"/\1:\ \"dev-develop\"/' composer.json
        composer update --prefer-dist --no-progress --no-interaction --no-dev
        php -dphar.readonly=0 utils/make-phar.php easyengine.phar
        sudo cp easyengine.phar /usr/local/bin/ee
        composer update --prefer-dist --no-progress --no-interaction --no-plugins

    - name: Test
      shell: 'script -q -e -c "bash {0}"'
      run: |
        set -e
        cd "$GITHUB_WORKSPACE/../easyengine"
        sudo -E ./vendor/bin/behat
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1